services:
  note-service:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["node", "index.js", "--host", "0.0.0.0", "--port", "3000", "--cache", "./cache"]